//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ev
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ev()
        {
            this.Musteris = new HashSet<Musteri>();
        }
    
        public int emlakNumarasi { get; set; }
        public int odaSayisi { get; set; }
        public int katNumarasi { get; set; }
        public string semt { get; set; }
        public int toplamEvAlani { get; set; }
        public System.DateTime yapimTarihi { get; set; }
        public string evTuru { get; set; }
        public string evDurumu { get; set; }
        public string il { get; set; }
        public string ilce { get; set; }
    
        public virtual KiralikEv KiralikEv { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Musteri> Musteris { get; set; }
        public virtual SatilikEv SatilikEv { get; set; }
    }
}
