//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak
{
    using System;
    using System.Collections.Generic;
    
    public partial class KiralikEv
    {
        public int emlakNumarasi { get; set; }
        public int kira { get; set; }
        public int depozito { get; set; }
    
        public virtual Ev Ev { get; set; }
    }
}
