//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public string kullaniciAd { get; set; }
        public string kullaniciSifre { get; set; }
        public int kullaniciID { get; set; }
        public string yetki { get; set; }
    }
}
