//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emlak
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteri
    {
        public int musteriID { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public int telefonNo { get; set; }
        public string mail { get; set; }
        public int tc { get; set; }
        public string adres { get; set; }
        public int emlakNumarasi { get; set; }
        public byte[] resim { get; set; }
    
        public virtual Ev Ev { get; set; }
    }
}
